server:
  port: 9010
spring:
  application:
    name: "web-app"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driveClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console: